# Generated by Django 3.2.3 on 2021-10-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(default='we are amazing', max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='fast', max_length=100),
        ),
    ]
